### ISSUE TITLE
"No compatible client available. Please change your scope" Crash

### ISSUE THREAD

**Issue by avvari-da** [dipinarora9/flutter_truecaller#7]
This crash is happening only when Truecaller app is not installed on the device.
Please help me understand the crash here. I have the executions inside a `try..catch` block in the Flutter code.

```
E/AndroidRuntime( 4628): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1276, result=0, data=null} to activity {com.example.app/com.example.app.MainActivity}: java.lang.RuntimeException: No compatible client available. Please change your scope
E/AndroidRuntime( 4628): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5097)
E/AndroidRuntime( 4628): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5138)
E/AndroidRuntime( 4628): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
E/AndroidRuntime( 4628): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime( 4628): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime( 4628): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2147)
E/AndroidRuntime( 4628): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime( 4628): 	at android.os.Looper.loop(Looper.java:237)
E/AndroidRuntime( 4628): 	at android.app.ActivityThread.main(ActivityThread.java:7814)
E/AndroidRuntime( 4628): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 4628): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/AndroidRuntime( 4628): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1068)
E/AndroidRuntime( 4628): Caused by: java.lang.RuntimeException: No compatible client available. Please change your scope
E/AndroidRuntime( 4628): 	at com.truecaller.android.sdk.TruecallerSDK.onActivityResultObtained(TruecallerSDK.java:198)
E/AndroidRuntime( 4628): 	at dipinarora9.flutter_truecaller.FlutterTruecallerPlugin$onAttachedToActivity$1.onActivityResult(FlutterTruecallerPlugin.kt:281)
E/AndroidRuntime( 4628): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEnginePluginRegistry.java:691)
E/AndroidRuntime( 4628): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry.onActivityResult(FlutterEnginePluginRegistry.java:378)
E/AndroidRuntime( 4628): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:619)
E/AndroidRuntime( 4628): 	at io.flutter.embedding.android.FlutterFragment.onActivityResult(FlutterFragment.java:704)
E/AndroidRuntime( 4628): 	at io.flutter.embedding.android.FlutterFragmentActivity.onActivityResult(FlutterFragmentActivity.java:509)
E/AndroidRuntime( 4628): 	at android.app.Activity.dispatchActivityResult(Activity.java:8292)
E/AndroidRuntime( 4628): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5090)
E/AndroidRuntime( 4628): 	... 11 more
I/Process ( 4628): Sending signal. PID: 4628 SIG: 9
```

**Comment by dipinarora9** [comment]
Hey @dheeraj2dj !
You are getting this error because you have set `sdkOptions: FlutterTruecallerScope.SDK_OPTION_WITHOUT_OTP` while initializing the SDK, change it to `FlutterTruecallerScope.SDK_OPTION_WITH_OTP` to use manual verification method.

**Comment by avvari-da** [comment]
@dipinarora9 But I don't want to use truecaller for manual verification, hence using `FlutterTruecallerScope.SDK_OPTION_WITHOUT_OTP`. Or irrespective, should I be using `FlutterTruecallerScope.SDK_OPTION_WITH_OTP`?

**Comment by sandeepgurram-bounce** [comment]
Any update on the issue ? I am facing the same problem. 

Even if we don't want to do OTP login, should we use `FlutterTruecallerScope.SDK_OPTION_WITH_OTP` ?

**Comment by dipinarora9** [comment]
If you are using SDK_OPTION_WITHOUT_OTP, then the truecaller app must be present in the user's device in order to verify using truecaller.
Do it like this,
set SDK options to SDK_OPTION_WITHOUT_OTP
bool result = await caller.isUsable;
check for this result variable if the result is true 
             then truecaller app is present, continue with the normal truecaller verification steps
else result is false
             then truecaller app is NOT present on the user's device then you need to use your own verification system.


OR else if you want to truecaller to verify those users' as well who don't have truecaller app, then you must put SDK options to SDK_OPTION_WITH_OTP so that the SDK can fallback to drop call/otp verification.
